### Menambahkan lembur baru
POST http://localhost:8000/overtime
Content-Type: application/json

{
    "date": "2024-1-22",
    "hours": "5",
    "description": "Overtime untuk proyek Z"
}

### Mendapatkan semua lembur
GET http://localhost:8000/overtime

### Mendapatkan lembur berdasarkan UUID
GET http://localhost:8000/overtime/d24c2d6c-873b-4f66-a886-e5636863b063

###approve
PUT http://localhost:8000/approve-overtime/d24c2d6c-873b-4f66-a886-e5636863b063

###reject
PUT http://localhost:8000/reject-overtime/87fcd53d-5613-434d-a0aa-f6c54e24d11e

###byuser
GET http://localhost:8000/overtime-history

###
//login admin
POST http://localhost:8000/Login
Content-Type: application/json
 
{
    "email":"admin@gmail.com",
    "password":"123"
}

###
//login user
POST http://localhost:8000/Login
Content-Type: application/json
 
{
    "email":"user@gmail.com",
    "password":"1234"
}
###
//Me
GET http://localhost:8000/me
###
//logout
DELETE http://localhost:8000/Logout


### Mengupdate lembur berdasarkan UUID
PUT http://localhost:8000/overtime/41c9f7ed-77ea-4d86-a1b8-24e00d21ea35
Content-Type: application/json

{
    "date": "2024-11-14",
    "hours": "3",
    "description": "Overtime untuk proyek Y"
}

### Menghapus lembur berdasarkan UUID
DELETE http://localhost:8000/overtime/{uuid}


